/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab07;

import java.awt.Color;
import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import java.applet.AudioClip;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Scanner;

/**
 *
 * @author luisa
 */
public class Interfaz extends javax.swing.JFrame {
    public double num1;
    public double num2;
    public String operador;  
    public boolean done=false;
    Scanner key1=new Scanner(System.in);
    int Numeros;
    
    
    
    public Interfaz() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/portada.png")));
        AudioClip inicio;
       inicio=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/chimes.wav"));
       inicio.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jPanel1 = new javax.swing.JPanel();
        eluno = new javax.swing.JButton();
        eldos = new javax.swing.JButton();
        eltres = new javax.swing.JButton();
        sumar = new javax.swing.JButton();
        resultado = new javax.swing.JButton();
        elcuatro = new javax.swing.JButton();
        elcinco = new javax.swing.JButton();
        elseis = new javax.swing.JButton();
        elsiete = new javax.swing.JButton();
        elocho = new javax.swing.JButton();
        elnueve = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        multiplicacion = new javax.swing.JButton();
        division = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        borrarnumero = new javax.swing.JButton();
        signo = new javax.swing.JButton();
        modulo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Pantalla = new javax.swing.JLabel();
        operaciones = new javax.swing.JLabel();
        claro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora ");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(425, 635));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eluno.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        eluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        eluno.setText("1");
        eluno.setBorderPainted(false);
        eluno.setFocusPainted(false);
        eluno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eluno.setPreferredSize(new java.awt.Dimension(50, 50));
        eluno.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        eluno.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        eluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elunoMouseClicked(evt);
            }
        });
        eluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elunoActionPerformed(evt);
            }
        });
        jPanel1.add(eluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        eldos.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        eldos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        eldos.setText("2");
        eldos.setBorderPainted(false);
        eldos.setFocusPainted(false);
        eldos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eldos.setPreferredSize(new java.awt.Dimension(50, 50));
        eldos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        eldos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        eldos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eldosMouseClicked(evt);
            }
        });
        eldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eldosActionPerformed(evt);
            }
        });
        jPanel1.add(eldos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        eltres.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        eltres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        eltres.setText("3");
        eltres.setBorderPainted(false);
        eltres.setFocusPainted(false);
        eltres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eltres.setPreferredSize(new java.awt.Dimension(50, 50));
        eltres.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        eltres.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        eltres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eltresMouseClicked(evt);
            }
        });
        eltres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eltresActionPerformed(evt);
            }
        });
        jPanel1.add(eltres, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        sumar.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        sumar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        sumar.setText("+");
        sumar.setBorderPainted(false);
        sumar.setFocusPainted(false);
        sumar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sumar.setPreferredSize(new java.awt.Dimension(50, 50));
        sumar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        sumar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        sumar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumarMouseClicked(evt);
            }
        });
        sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarActionPerformed(evt);
            }
        });
        jPanel1.add(sumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        resultado.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        resultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono3v.png"))); // NOI18N
        resultado.setText("=");
        resultado.setBorderPainted(false);
        resultado.setFocusPainted(false);
        resultado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resultado.setPreferredSize(new java.awt.Dimension(50, 50));
        resultado.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        resultado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono3v.png"))); // NOI18N
        resultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultadoMouseClicked(evt);
            }
        });
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });
        jPanel1.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        elcuatro.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        elcuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        elcuatro.setText("4");
        elcuatro.setBorderPainted(false);
        elcuatro.setFocusPainted(false);
        elcuatro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        elcuatro.setPreferredSize(new java.awt.Dimension(50, 50));
        elcuatro.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        elcuatro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        elcuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elcuatroMouseClicked(evt);
            }
        });
        elcuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elcuatroActionPerformed(evt);
            }
        });
        jPanel1.add(elcuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        elcinco.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        elcinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        elcinco.setText("5");
        elcinco.setBorderPainted(false);
        elcinco.setFocusPainted(false);
        elcinco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        elcinco.setPreferredSize(new java.awt.Dimension(50, 50));
        elcinco.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        elcinco.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        elcinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elcincoMouseClicked(evt);
            }
        });
        elcinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elcincoActionPerformed(evt);
            }
        });
        jPanel1.add(elcinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        elseis.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        elseis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        elseis.setText("6");
        elseis.setBorderPainted(false);
        elseis.setFocusPainted(false);
        elseis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        elseis.setPreferredSize(new java.awt.Dimension(50, 50));
        elseis.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        elseis.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        elseis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elseisMouseClicked(evt);
            }
        });
        elseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elseisActionPerformed(evt);
            }
        });
        jPanel1.add(elseis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        elsiete.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        elsiete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        elsiete.setText("7");
        elsiete.setBorderPainted(false);
        elsiete.setFocusPainted(false);
        elsiete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        elsiete.setPreferredSize(new java.awt.Dimension(50, 50));
        elsiete.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        elsiete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        elsiete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elsieteMouseClicked(evt);
            }
        });
        elsiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elsieteActionPerformed(evt);
            }
        });
        jPanel1.add(elsiete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        elocho.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        elocho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        elocho.setText("8");
        elocho.setBorderPainted(false);
        elocho.setFocusPainted(false);
        elocho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        elocho.setPreferredSize(new java.awt.Dimension(50, 50));
        elocho.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        elocho.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        elocho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elochoMouseClicked(evt);
            }
        });
        elocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elochoActionPerformed(evt);
            }
        });
        jPanel1.add(elocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        elnueve.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        elnueve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        elnueve.setText("9");
        elnueve.setBorderPainted(false);
        elnueve.setFocusPainted(false);
        elnueve.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        elnueve.setPreferredSize(new java.awt.Dimension(50, 50));
        elnueve.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        elnueve.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        elnueve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elnueveMouseClicked(evt);
            }
        });
        elnueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elnueveActionPerformed(evt);
            }
        });
        jPanel1.add(elnueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        cero.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        cero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        cero.setText("0");
        cero.setBorderPainted(false);
        cero.setFocusPainted(false);
        cero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cero.setPreferredSize(new java.awt.Dimension(50, 50));
        cero.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        cero.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        cero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ceroMouseClicked(evt);
            }
        });
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });
        jPanel1.add(cero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        resta.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        resta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        resta.setText("-");
        resta.setBorderPainted(false);
        resta.setFocusPainted(false);
        resta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resta.setPreferredSize(new java.awt.Dimension(50, 50));
        resta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        resta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        resta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restaMouseClicked(evt);
            }
        });
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });
        jPanel1.add(resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        multiplicacion.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        multiplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        multiplicacion.setText("x");
        multiplicacion.setBorderPainted(false);
        multiplicacion.setFocusPainted(false);
        multiplicacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        multiplicacion.setPreferredSize(new java.awt.Dimension(50, 50));
        multiplicacion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        multiplicacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        multiplicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicacionMouseClicked(evt);
            }
        });
        multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(multiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        division.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        division.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        division.setText("÷");
        division.setBorderPainted(false);
        division.setFocusPainted(false);
        division.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        division.setPreferredSize(new java.awt.Dimension(50, 50));
        division.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        division.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        division.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisionMouseClicked(evt);
            }
        });
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });
        jPanel1.add(division, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        clear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        clear.setText("C");
        clear.setBorderPainted(false);
        clear.setFocusPainted(false);
        clear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clear.setPreferredSize(new java.awt.Dimension(50, 50));
        clear.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        clear.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        punto.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        punto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        punto.setText(".");
        punto.setBorderPainted(false);
        punto.setFocusPainted(false);
        punto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        punto.setPreferredSize(new java.awt.Dimension(50, 50));
        punto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        punto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        punto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                puntoMouseClicked(evt);
            }
        });
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });
        jPanel1.add(punto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        borrarnumero.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        borrarnumero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        borrarnumero.setText("←");
        borrarnumero.setBorderPainted(false);
        borrarnumero.setFocusPainted(false);
        borrarnumero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borrarnumero.setPreferredSize(new java.awt.Dimension(50, 50));
        borrarnumero.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        borrarnumero.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        borrarnumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarnumeroMouseClicked(evt);
            }
        });
        borrarnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarnumeroActionPerformed(evt);
            }
        });
        jPanel1.add(borrarnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        signo.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        signo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        signo.setText("+/-");
        signo.setBorderPainted(false);
        signo.setContentAreaFilled(false);
        signo.setFocusPainted(false);
        signo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signo.setPreferredSize(new java.awt.Dimension(50, 50));
        signo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        signo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        signo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signoMouseClicked(evt);
            }
        });
        signo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoActionPerformed(evt);
            }
        });
        jPanel1.add(signo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 53, -1));

        modulo.setBackground(new java.awt.Color(0, 0, 0));
        modulo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        modulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono1v.png"))); // NOI18N
        modulo.setText("%");
        modulo.setBorderPainted(false);
        modulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modulo.setPreferredSize(new java.awt.Dimension(50, 50));
        modulo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1 (1).png"))); // NOI18N
        modulo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicono2v.png"))); // NOI18N
        modulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moduloMouseClicked(evt);
            }
        });
        modulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloActionPerformed(evt);
            }
        });
        jPanel1.add(modulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jPanel2.setBackground(new java.awt.Color(218, 255, 255));

        Pantalla.setBackground(new java.awt.Color(224, 253, 255));
        Pantalla.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Pantalla.setForeground(new java.awt.Color(54, 46, 46));
        Pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Pantalla.setFocusable(false);
        Pantalla.setOpaque(true);
        Pantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PantallaKeyPressed(evt);
            }
        });

        operaciones.setBackground(new java.awt.Color(210, 253, 238));
        operaciones.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        claro.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        claro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/claro.png"))); // NOI18N
        claro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        claro.setBorderPainted(false);
        claro.setPreferredSize(new java.awt.Dimension(40, 40));
        claro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                claroMouseClicked(evt);
            }
        });
        claro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(operaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(claro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(claro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void elunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elunoActionPerformed
        this.Pantalla.setText(this.Pantalla.getText()+"1");
        
    }//GEN-LAST:event_elunoActionPerformed

    private void eldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eldosActionPerformed
         this.Pantalla.setText(this.Pantalla.getText()+"2");
    }//GEN-LAST:event_eldosActionPerformed

    private void eltresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eltresActionPerformed
         this.Pantalla.setText(this.Pantalla.getText()+"3");
    }//GEN-LAST:event_eltresActionPerformed

    private void elcuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elcuatroActionPerformed
         this.Pantalla.setText(this.Pantalla.getText()+"4");
    }//GEN-LAST:event_elcuatroActionPerformed

    private void elcincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elcincoActionPerformed
    this.Pantalla.setText(this.Pantalla.getText()+"5");
    }//GEN-LAST:event_elcincoActionPerformed

    private void elseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elseisActionPerformed
        this.Pantalla.setText(this.Pantalla.getText()+"6");
    }//GEN-LAST:event_elseisActionPerformed

    private void elsieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elsieteActionPerformed
         this.Pantalla.setText(this.Pantalla.getText()+"7");
    }//GEN-LAST:event_elsieteActionPerformed

    private void elochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elochoActionPerformed
        this.Pantalla.setText(this.Pantalla.getText()+"8");
    }//GEN-LAST:event_elochoActionPerformed

    private void elnueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elnueveActionPerformed
         this.Pantalla.setText(this.Pantalla.getText()+"9");
    }//GEN-LAST:event_elnueveActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
      this.Pantalla.setText(this.Pantalla.getText()+"0");
    }//GEN-LAST:event_ceroActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        this.Pantalla.setText("");
         this.operaciones.setText("");
    }//GEN-LAST:event_clearActionPerformed

                       
    
    
    private void sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarActionPerformed
        Suma s1=new Suma(this.num1=Double.parseDouble(this.Pantalla.getText()),0);
        this.operador="+";
        this.Pantalla.setText("");
        this.operaciones.setText(this.decimal(num1)+operador);
    }//GEN-LAST:event_sumarActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
     
        
     Suma s2=new Suma(num1,this.num2=Double.parseDouble(this.Pantalla.getText()));
     if (operador=="+"){  this.Pantalla.setText(this.decimal(s2.execute(num1, num2)));
     this.operaciones.setText(this.decimal(num1)+"+"+this.decimal(num2));
   
     
     } 
     
     Resta r2=new Resta (num1,this.num2=Double.parseDouble(this.Pantalla.getText()));
     if (operador=="-") {this.Pantalla.setText(this.decimal(r2.execute(num1, num2)));
     this.operaciones.setText(this.decimal(num1)+"-"+this.decimal(num2));}
     
    Multiplicacion m2=new Multiplicacion (num1,this.num2=Double.parseDouble(this.Pantalla.getText()));
     if (operador=="x"){ this.Pantalla.setText(this.decimal(m2.execute(num1, num2))); 
     this.operaciones.setText(this.decimal(num1)+"x"+this.decimal(num2));}
     
      Division d2=new Division (num1,this.num2=Double.parseDouble(this.Pantalla.getText()));
     if (operador=="÷") { 
         if(num2==0){this.Pantalla.setText("Indeterminado"); this.operaciones.setText(this.decimal(num1)+"÷"+this.decimal(num2));
       AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Critical Stop.wav"));
       sound.play();
         }
         
         else {
         this.Pantalla.setText(this.decimal(d2.execute(num1, num2))); this.operaciones.setText(this.decimal(num1)+"÷"+this.decimal(num2));} 
         }
     
     Module module2=new Module (num1,this.num2=Double.parseDouble(this.Pantalla.getText()));
     if (operador=="%") {this.Pantalla.setText(this.decimal(module2.execute(num1, num2)));
     this.operaciones.setText(this.decimal(num1)+"%"+this.decimal(num2));}
     
     
    }//GEN-LAST:event_resultadoActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
         if(!(this.Pantalla.getText().contains(".")))
           this.Pantalla.setText(this.Pantalla.getText()+".");
                 
    }//GEN-LAST:event_puntoActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
       Resta r1=new Resta (this.num1=Double.parseDouble(this.Pantalla.getText()),0);
        this.operador="-";
        this.Pantalla.setText("");
         this.operaciones.setText(this.decimal(num1)+operador);
    }//GEN-LAST:event_restaActionPerformed

    private void multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacionActionPerformed
        Multiplicacion m1=new Multiplicacion (this.num1=Double.parseDouble(this.Pantalla.getText()),0);
        this.operador="x";
        this.Pantalla.setText("");
        this.operaciones.setText(this.decimal(num1)+operador);
    }//GEN-LAST:event_multiplicacionActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
        Division d1=new Division (this.num1=Double.parseDouble(this.Pantalla.getText()),0);
        this.operador="÷";
        this.Pantalla.setText("");
        this.operaciones.setText(this.decimal(num1)+operador);
    }//GEN-LAST:event_divisionActionPerformed

    private void borrarnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarnumeroActionPerformed
        String borrar="";
        borrar=this.Pantalla.getText();
        if(borrar.length()>0){
            borrar=borrar.substring(0,borrar.length()-1);
            this.Pantalla.setText(borrar);
        }

    }//GEN-LAST:event_borrarnumeroActionPerformed

    private void signoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoActionPerformed
        Double num;
        String datos;
        datos=this.Pantalla.getText();
        if(datos.length()>0){
        num=(-1)*Double.parseDouble(datos);
        
       this.Pantalla.setText(this.decimal(num));
       this.operaciones.setText(this.decimal(num));
        
        }
    }//GEN-LAST:event_signoActionPerformed

    boolean oscuro=false;
    
    private void claroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claroActionPerformed
        
        if (!oscuro){
        jPanel2.setBackground(Color.decode("#212b41"));
        this.Pantalla.setBackground(Color.decode("#212b41"));
        jPanel1.setBackground(Color.decode("#212b41"));
        this.Pantalla.setForeground(Color.decode("#0db387"));
        this.operaciones.setForeground(Color.decode("#0db387"));
        
        tema(cero);
        tema(eluno);
        tema(eldos);
        tema(eltres);
        tema(elcuatro);
        tema(elcinco);
        tema(elseis);
        tema(elsiete);
        tema(elocho); 
        tema(elnueve);
        tema(punto);
        tema(signo);
        
        tema1(clear);
        tema1(division);
        tema1(multiplicacion);
        tema1(resta);
        tema1(sumar);
        tema1(borrarnumero);
        tema1(modulo);
        
        
        claro.setIcon(new ImageIcon(getClass().getResource("/Imagenes/oscuro.png")));
        resultado.setIcon(new ImageIcon(getClass().getResource("/Imagenes/resultado.png")));
        resultado.setPressedIcon(new ImageIcon(getClass().getResource("/Imagenes/iconooscuro1.png")));
        resultado.setRolloverIcon(new ImageIcon(getClass().getResource("/Imagenes/resultado1.png")));
        resultado.setForeground(Color.white);
        oscuro=true;
        }
        
        else { 
            
       AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Battery Critical.wav"));
       sound.play();
       
            Interfaz tem=new Interfaz();
            this.dispose();
            tem.setVisible(true);
        }
        
        
    }//GEN-LAST:event_claroActionPerformed

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
       
       
       AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Background.wav"));
       sound.play();
    }//GEN-LAST:event_clearMouseClicked

    private void resultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultadoMouseClicked
      
        AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Notify Calendar.wav"));
       sound.play();
       
        if(num2==0){sound.stop();}
    }//GEN-LAST:event_resultadoMouseClicked

    private void borrarnumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarnumeroMouseClicked
       
       if(this.Pantalla.getText()==""){
       AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Background.wav"));
       sound.play();}
    }//GEN-LAST:event_borrarnumeroMouseClicked

    private void claroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claroMouseClicked
       AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Battery Low.wav"));
       sound.play();
    }//GEN-LAST:event_claroMouseClicked

    private void elunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elunoMouseClicked
       AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_elunoMouseClicked

    private void eldosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eldosMouseClicked
         AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_eldosMouseClicked

    private void eltresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eltresMouseClicked
        // TODO add your handling code here:
         AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_eltresMouseClicked

    private void ceroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ceroMouseClicked
        // TODO add your handling code here:
         AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_ceroMouseClicked

    private void elcuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elcuatroMouseClicked
        // TODO add your handling code here:
         AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_elcuatroMouseClicked

    private void elcincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elcincoMouseClicked
        // TODO add your handling code here:
         AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_elcincoMouseClicked

    private void elseisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elseisMouseClicked
        // TODO add your handling code here:
         AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_elseisMouseClicked

    private void elsieteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elsieteMouseClicked
        // TODO add your handling code here:
         AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_elsieteMouseClicked

    private void elochoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elochoMouseClicked
        // TODO add your handling code here:
         AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_elochoMouseClicked

    private void elnueveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elnueveMouseClicked
        // TODO add your handling code here:
         AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_elnueveMouseClicked

    private void sumarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumarMouseClicked
        // TODO add your handling code here:
         AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_sumarMouseClicked

    private void restaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaMouseClicked
        // TODO add your handling code here:
         AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_restaMouseClicked

    private void multiplicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicacionMouseClicked
        // TODO add your handling code here:
         AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_multiplicacionMouseClicked

    private void divisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionMouseClicked
        // TODO add your handling code here:
         AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_divisionMouseClicked

    private void signoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoMouseClicked
        // TODO add your handling code here:
         AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_signoMouseClicked

    private void puntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puntoMouseClicked
        // TODO add your handling code here:
         AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_puntoMouseClicked

    private void moduloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloActionPerformed
       Module m1=new Module (this.num1=Double.parseDouble(this.Pantalla.getText()),0);
        this.operador="%";
        this.Pantalla.setText("");
         this.operaciones.setText(this.decimal(num1)+operador);
    }//GEN-LAST:event_moduloActionPerformed

    private void moduloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moduloMouseClicked
           AudioClip sound;
       sound=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Windows Balloon.wav"));
       sound.play();
    }//GEN-LAST:event_moduloMouseClicked

    private void PantallaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PantallaKeyPressed
      Numeros=key1.nextInt();
        this.Pantalla.setText(""+Numeros);
    }//GEN-LAST:event_PantallaKeyPressed

    public void tema1(JButton btn){
    
         
        btn.setIcon(new ImageIcon(getClass().getResource("/Imagenes/iconooscuro1.png")));
        btn.setPressedIcon(new ImageIcon(getClass().getResource("/Imagenes/iconooscuro1.png")));
        btn.setRolloverIcon(new ImageIcon(getClass().getResource("/Imagenes/iconooscuro2.png")));
        btn.setForeground(Color.decode("#0db387"));

    }
    
    public void tema(JButton btn){
        
        btn.setIcon(new ImageIcon(getClass().getResource("/Imagenes/iconooscuro1.png")));
        btn.setPressedIcon(new ImageIcon(getClass().getResource("/Imagenes/iconooscuro1.png")));
        btn.setRolloverIcon(new ImageIcon(getClass().getResource("/Imagenes/iconooscuro2.png")));
        btn.setForeground(Color.orange);
    
    }
    
    
    public String decimal(double resultado){
        String retorno="";
        retorno=Double.toString(resultado);
        
        if(resultado%1==0){
            retorno=retorno.substring(0,retorno.length()-2);
        
        }
        
        return retorno;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pantalla;
    private javax.swing.JButton borrarnumero;
    private javax.swing.JButton cero;
    private javax.swing.JButton claro;
    private javax.swing.JButton clear;
    private javax.swing.JButton division;
    private javax.swing.JButton elcinco;
    private javax.swing.JButton elcuatro;
    private javax.swing.JButton eldos;
    private javax.swing.JButton elnueve;
    private javax.swing.JButton elocho;
    private javax.swing.JButton elseis;
    private javax.swing.JButton elsiete;
    private javax.swing.JButton eltres;
    private javax.swing.JButton eluno;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton modulo;
    private javax.swing.JButton multiplicacion;
    private javax.swing.JLabel operaciones;
    private javax.swing.JButton punto;
    private javax.swing.JButton resta;
    private javax.swing.JButton resultado;
    private javax.swing.JButton signo;
    private javax.swing.JButton sumar;
    // End of variables declaration//GEN-END:variables
}
