/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab07;

/**
 *
 * @author luisa
 */
public class Interfaz extends javax.swing.JFrame {
    public double num1;
    public double num2;
    public String operador;  
    public boolean done;

    
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pantalla = new javax.swing.JLabel();
        eluno = new javax.swing.JButton();
        eldos = new javax.swing.JButton();
        eltres = new javax.swing.JButton();
        sumar = new javax.swing.JButton();
        resultado = new javax.swing.JButton();
        elcuatro = new javax.swing.JButton();
        elcinco = new javax.swing.JButton();
        elseis = new javax.swing.JButton();
        elsiete = new javax.swing.JButton();
        elocho = new javax.swing.JButton();
        elnueve = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        multiplicacion = new javax.swing.JButton();
        division = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        borrarnumero = new javax.swing.JButton();
        signo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de lui");
        setPreferredSize(new java.awt.Dimension(350, 500));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        Pantalla.setBackground(new java.awt.Color(255, 255, 255));
        Pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Pantalla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        Pantalla.setOpaque(true);

        eluno.setText("1");
        eluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elunoActionPerformed(evt);
            }
        });

        eldos.setText("2");
        eldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eldosActionPerformed(evt);
            }
        });

        eltres.setText("3");
        eltres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eltresActionPerformed(evt);
            }
        });

        sumar.setText("+");
        sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarActionPerformed(evt);
            }
        });

        resultado.setText("=");
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        elcuatro.setText("4");
        elcuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elcuatroActionPerformed(evt);
            }
        });

        elcinco.setText("5");
        elcinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elcincoActionPerformed(evt);
            }
        });

        elseis.setText("6");
        elseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elseisActionPerformed(evt);
            }
        });

        elsiete.setText("7");
        elsiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elsieteActionPerformed(evt);
            }
        });

        elocho.setText("8");
        elocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elochoActionPerformed(evt);
            }
        });

        elnueve.setText("9");
        elnueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elnueveActionPerformed(evt);
            }
        });

        cero.setText("0");
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });

        resta.setText("-");
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });

        multiplicacion.setText("*");
        multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacionActionPerformed(evt);
            }
        });

        division.setText("/");
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });

        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        punto.setText(".");
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        borrarnumero.setText("x");
        borrarnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarnumeroActionPerformed(evt);
            }
        });

        signo.setText("+/-");
        signo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(signo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(elseis)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(eluno)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cero)
                                        .addComponent(eldos))
                                    .addGap(24, 24, 24)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(eltres)
                                        .addComponent(punto)))
                                .addComponent(elnueve))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(elcuatro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(elcinco))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(clear)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(elsiete)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(elocho))))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultado)
                            .addComponent(sumar)
                            .addComponent(division)
                            .addComponent(multiplicacion)
                            .addComponent(resta))))
                .addGap(0, 99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(borrarnumero)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(borrarnumero)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(division)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(clear)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elsiete)
                    .addComponent(elocho)
                    .addComponent(elnueve)
                    .addComponent(multiplicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elcuatro)
                    .addComponent(elcinco)
                    .addComponent(elseis)
                    .addComponent(resta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eluno)
                    .addComponent(eldos)
                    .addComponent(eltres)
                    .addComponent(sumar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cero)
                        .addComponent(resultado)
                        .addComponent(punto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(signo)))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elunoActionPerformed
        this.Pantalla.setText(this.Pantalla.getText()+"1");
    }//GEN-LAST:event_elunoActionPerformed

    private void eldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eldosActionPerformed
         this.Pantalla.setText(this.Pantalla.getText()+"2");
    }//GEN-LAST:event_eldosActionPerformed

    private void eltresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eltresActionPerformed
         this.Pantalla.setText(this.Pantalla.getText()+"3");
    }//GEN-LAST:event_eltresActionPerformed

    private void elcuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elcuatroActionPerformed
         this.Pantalla.setText(this.Pantalla.getText()+"4");
    }//GEN-LAST:event_elcuatroActionPerformed

    private void elcincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elcincoActionPerformed
    this.Pantalla.setText(this.Pantalla.getText()+"5");
    }//GEN-LAST:event_elcincoActionPerformed

    private void elseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elseisActionPerformed
        this.Pantalla.setText(this.Pantalla.getText()+"6");
    }//GEN-LAST:event_elseisActionPerformed

    private void elsieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elsieteActionPerformed
         this.Pantalla.setText(this.Pantalla.getText()+"7");
    }//GEN-LAST:event_elsieteActionPerformed

    private void elochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elochoActionPerformed
        this.Pantalla.setText(this.Pantalla.getText()+"8");
    }//GEN-LAST:event_elochoActionPerformed

    private void elnueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elnueveActionPerformed
         this.Pantalla.setText(this.Pantalla.getText()+"9");
    }//GEN-LAST:event_elnueveActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
      this.Pantalla.setText(this.Pantalla.getText()+"0");
    }//GEN-LAST:event_ceroActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        this.Pantalla.setText("");
    }//GEN-LAST:event_clearActionPerformed

                       
    
    
    private void sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarActionPerformed
        Suma s1=new Suma(this.num1=Double.parseDouble(this.Pantalla.getText()),0);
        this.operador="+";
        this.Pantalla.setText("");
    }//GEN-LAST:event_sumarActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
     Suma s2=new Suma(num1,this.num2=Double.parseDouble(this.Pantalla.getText()));
     if (operador=="+"){  this.Pantalla.setText(this.decimal(s2.execute(num1, num2)));
    // num1=0;
     //num2=0;
     //done=this.Pantalla.isVisible();
     //if(done!=false) this.Pantalla.setText("");
     }
     
     Resta r2=new Resta (num1,this.num2=Double.parseDouble(this.Pantalla.getText()));
     if (operador=="-") this.Pantalla.setText(this.decimal(r2.execute(num1, num2)));
     
    Multiplicacion m2=new Multiplicacion (num1,this.num2=Double.parseDouble(this.Pantalla.getText()));
     if (operador=="*") this.Pantalla.setText(this.decimal(m2.execute(num1, num2))); 
     
      Division d2=new Division (num1,this.num2=Double.parseDouble(this.Pantalla.getText()));
     if (operador=="/") { 
         if(num2==0){this.Pantalla.setText("Indeterminado");}
         
         else {
         this.Pantalla.setText(this.decimal(d2.execute(num1, num2)));} 
         }
    }//GEN-LAST:event_resultadoActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
         if(!(this.Pantalla.getText().contains(".")))
           this.Pantalla.setText(this.Pantalla.getText()+".");
                 
    }//GEN-LAST:event_puntoActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
       Resta r1=new Resta (this.num1=Double.parseDouble(this.Pantalla.getText()),0);
        this.operador="-";
        this.Pantalla.setText("");
    }//GEN-LAST:event_restaActionPerformed

    private void multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacionActionPerformed
        Multiplicacion m1=new Multiplicacion (this.num1=Double.parseDouble(this.Pantalla.getText()),0);
        this.operador="*";
        this.Pantalla.setText("");
    }//GEN-LAST:event_multiplicacionActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
        Division d1=new Division (this.num1=Double.parseDouble(this.Pantalla.getText()),0);
        this.operador="/";
        this.Pantalla.setText("");
    }//GEN-LAST:event_divisionActionPerformed

    private void borrarnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarnumeroActionPerformed
        String borrar="";
        borrar=this.Pantalla.getText();
        if(borrar.length()>0){
            borrar=borrar.substring(0,borrar.length()-1);
            this.Pantalla.setText(borrar);
        }

    }//GEN-LAST:event_borrarnumeroActionPerformed

    private void signoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoActionPerformed
        Double num;
        String datos;
        datos=this.Pantalla.getText();
        if(datos.length()>0){
        num=(-1)*Double.parseDouble(datos);
        
       this.Pantalla.setText(this.decimal(num));
        
        }
    }//GEN-LAST:event_signoActionPerformed

    public String decimal(double resultado){
        String retorno="";
        retorno=Double.toString(resultado);
        
        if(resultado%1==0){
            retorno=retorno.substring(0,retorno.length()-2);
        
        }
        
        return retorno;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pantalla;
    private javax.swing.JButton borrarnumero;
    private javax.swing.JButton cero;
    private javax.swing.JButton clear;
    private javax.swing.JButton division;
    private javax.swing.JButton elcinco;
    private javax.swing.JButton elcuatro;
    private javax.swing.JButton eldos;
    private javax.swing.JButton elnueve;
    private javax.swing.JButton elocho;
    private javax.swing.JButton elseis;
    private javax.swing.JButton elsiete;
    private javax.swing.JButton eltres;
    private javax.swing.JButton eluno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton multiplicacion;
    private javax.swing.JButton punto;
    private javax.swing.JButton resta;
    private javax.swing.JButton resultado;
    private javax.swing.JButton signo;
    private javax.swing.JButton sumar;
    // End of variables declaration//GEN-END:variables
}
